Repository Dhaneha-Shiyamkumar/open-hackday-2020, pull requests merged in 2020-10, with the labels that each got.

#1 added 1.html file
  1.html
  happy.jpg
Labels: hacktoberfest, hacktoberfest2020

#2 Create rank.java
  rank.java
Labels: hacktoberfest, hacktoberfest2020

#3 Create README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest2020

#4 Create pangrams.java
  pangrams.java
Labels: hacktoberfest-accepted, hacktoberfest2020

#5 added a new file
  hackday.html
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2020
